eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://j10c206.p.ssafy.io:3306/dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true

swagger:
  server: http://localhost:8081

notification:
  fundingReview-url: http://backend-notification/api/v1/notification/fundingReview/