eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://3.34.127.65:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://j10c206.p.ssafy.io:3306/prod?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true

swagger:
  server: https://giveus.site

host:
  address: https://giveus.site

pay:
  kakao:
    donate:
      success_url: ${host.address}/payment/kakao/donate/success
      cancel_url: ${host.address}/payment/kakao/donate/cancel
      fail_url: ${host.address}/payment/kakao/donate/fail
    recharge:
      success_url: ${host.address}/payment/kakao/recharge/success
      cancel_url: ${host.address}/payment/kakao/recharge/cancel
      fail_url: ${host.address}/payment/kakao/recharge/fail
  toss:
    donate:
      success_url: ${host.address}/payment/toss/donate/success
      fail_url: ${host.address}/payment/toss/donate/fail
    recharge:
      success_url: ${host.address}/payment/toss/recharge/success
      fail_url: ${host.address}/payment/toss/recharge/fail