eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://j10c206.p.ssafy.io:3306/dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true

swagger:
  server: http://localhost:8081

host:
  address: http://localhost:8081

pay:
  kakao:
    donate:
      success_url: ${host.address}/api/v1/payment/kakao/donate/success
      cancel_url: ${host.address}/api/v1/payment/kakao/donate/cancel
      fail_url: ${host.address}/api/v1/payment/kakao/donate/fail
    recharge:
      success_url: ${host.address}/api/v1/payment/kakao/recharge/success
      cancel_url: ${host.address}/api/v1/payment/kakao/recharge/cancel
      fail_url: ${host.address}/api/v1/payment/kakao/recharge/fail
  toss:
    donate:
      success_url: ${host.address}/api/v1/payment/toss/donate/success
      fail_url: ${host.address}/api/v1/payment/toss/donate/fail