eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://3.34.127.65:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://j10c206.p.ssafy.io:3306/prod?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5b58cb5c937215cb68194d123d242c8b #
            client-authentication-method: client_secret_post #
            authorization-grant-type: authorization_code #
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "https://admin.giveus.site/admin/login/oauth2/code/kakao" #
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize #
            token-uri: https://kauth.kakao.com/oauth/token #
            user-info-uri: https://kapi.kakao.com/v2/user/me
            #            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

redirect:
  success:
    https://admin.giveus.site/login/oauth2

swagger:
  server: https://giveus.site

coolsms:
  env:
    phone: '01077124919'
  api:
    key: NCSYSZCQO6D1CTLP
    secret: 9X3M3G3EEEEDSTZJRZKHQWTCUTILFKV8

notification:
  usageHistory-url: https://backend-notification/api/v1/notification/usageHistory/